### ISSUE TITLE
Fastspeech2, 보코더 pre-trained ckpt

### ISSUE THREAD

**Issue by WooranJo** [hwRG/End-to-End-TTS-Fine-Tune#1]
안녕하세요. 소중한 자료 공유 감사합니다.
이 프로젝트를 통해 TTS 모델을 공부하고 있는데, 요청드릴 부분이 있어 이렇게 의견 남깁니다.

readme에 남겨져 있는 링크가 사라졌는지 파일을 찾을 수가 없는데,
혹시 fastspeech2, 보코더 ckpt 파일을 받을 수 있을까요?

**Comment by Foreist** [comment]
저도 ckpt 링크 좀 부탁드립니다!

**Comment by skyoum00** [comment]
저도 좀 ckpt 좀 받을 수 있을까요?

**Comment by hwRG** [comment]
안녕하세요, 답변이 많이 늦었습니다.

요청 주신 체크포인트 링크는 README에 새로 등록해 두었습니다.
FastSpeech2 : https://drive.google.com/drive/folders/141Q7XcxIVVgegMQrz6LNspIDrteUNIrA
HiFi-GAN : https://drive.google.com/drive/folders/1-eEYTB5Av9jNql0WGBlRoi-WH2J7bp5Y (저자분 공식 체크포인트, UNIVERSAL_V1 권장)

다만 한국어 체크포인트 공유 이슈로 인해, 완벽한 체크포인트가 아니라는 점은 양해 부탁드립니다.
또한, 사용 시 모델 구조가 맞지 않은 경우가 있어, load_state_dict 시 strict=False를 적절히 활용해주시기 바랍니다.

감사합니다.
